"""changed the processed_at field to use the utc timezone

Revision ID: 4ffd8d76a8cb
Revises: 9ee49095f802
Create Date: 2026-05-10 02:00:43.687571

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffd8d76a8cb'
down_revision: Union[str, Sequence[str], None] = '9ee49095f802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
