"""make job_applicant email and job id unique

Revision ID: 90865b6f4231
Revises: b3f29a1d8e05
Create Date: 2026-03-16 15:08:36.362502

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90865b6f4231'
down_revision: Union[str, Sequence[str], None] = 'b3f29a1d8e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
