"""added processed_webhook_event table for Idempotency

Revision ID: 95b50087dfdc
Revises: bf5a4689e569
Create Date: 2026-05-09 21:25:15.567781

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b50087dfdc'
down_revision: Union[str, Sequence[str], None] = 'bf5a4689e569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
