"""added processed_webhook_event table for Idempotency-2

Revision ID: 9ee49095f802
Revises: 1eea62316818
Create Date: 2026-05-10 00:35:14.786169

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee49095f802'
down_revision: Union[str, Sequence[str], None] = '1eea62316818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processedwebhookevent',
    sa.Column('svix_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('svix_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processedwebhookevent')
    # ### end Alembic commands ###
