"""init

Revision ID: a7cbfb05b63c
Revises: 
Create Date: 2026-02-20 23:09:38.401620

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
import pgvector # <--- CHANGED THIS


# revision identifiers, used by Alembic.
revision: str = 'a7cbfb05b63c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. ENABLE THE VECTOR EXTENSION FIRST
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('user_type', sa.Enum('APPLICANT', 'RECRUITER', 'ADMIN', name='usertype'), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    
    op.create_table('job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('applicant_count', sa.Integer(), nullable=False),
    sa.Column('location', sa.Enum('REMOTE', 'ONSITE', 'HYBRID', name='locationtype'), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('responsibilities', sa.JSON(), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    # CHANGED TO pgvector.sqlalchemy.Vector
    sa.Column('description_embedding', pgvector.sqlalchemy.Vector(3072), nullable=True),
    sa.Column('requirements_embedding', pgvector.sqlalchemy.Vector(3072), nullable=True),
    sa.Column('responsibilities_embedding', pgvector.sqlalchemy.Vector(3072), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('jobapplicant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_post_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('s3_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('progress_status', sa.Enum('APPLIED', 'SHORTLISTED', 'INTERVIEWING', 'REJECTED', 'HIRED', name='progressstatus'), nullable=False),
    sa.Column('seniority_level', sa.Enum('INTERN', 'JUNIOR', 'MID', 'SENIOR', name='senioritystatus'), nullable=True),
    sa.Column('application_status', sa.Enum('PENDING', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='applicationstatus'), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('failed_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    # CHANGED TO pgvector.sqlalchemy.Vector
    sa.Column('embedded_value', pgvector.sqlalchemy.Vector(3072), nullable=True),
    sa.ForeignKeyConstraint(['job_post_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobapplicant_s3_path'), 'jobapplicant', ['s3_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobapplicant_s3_path'), table_name='jobapplicant')
    op.drop_table('jobapplicant')
    op.drop_table('job')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###