"""add retry_count to jobapplicant

Revision ID: b161c55ab7e8
Revises: b515ae5d5e16
Create Date: 2026-03-16 16:02:00.437604

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b161c55ab7e8'
down_revision: Union[str, Sequence[str], None] = 'b515ae5d5e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
