"""empty message

Revision ID: b515ae5d5e16
Revises: 90865b6f4231
Create Date: 2026-03-16 15:55:07.011999

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b515ae5d5e16'
down_revision: Union[str, Sequence[str], None] = '90865b6f4231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobapplicant', sa.Column('retry_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobapplicant', 'retry_count')
    # ### end Alembic commands ###
