"""added clerk_user_id

Revision ID: d57c344b4c21
Revises: 69fea7ede492
Create Date: 2026-05-09 20:45:46.266886

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd57c344b4c21'
down_revision: Union[str, Sequence[str], None] = '69fea7ede492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('clerk_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_user_clerk_user_id'), 'user', ['clerk_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_clerk_user_id'), table_name='user')
    op.drop_column('user', 'clerk_user_id')
    # ### end Alembic commands ###
